---
development:
  cloud_name: edmundleex
  api_key: '411354535945527'
  api_secret: WfZExNT6x0CWAmiAOE7wHTCb7FU
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: edmundleex
  api_key: '411354535945527'
  api_secret: WfZExNT6x0CWAmiAOE7wHTCb7FU
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: edmundleex
  api_key: '411354535945527'
  api_secret: WfZExNT6x0CWAmiAOE7wHTCb7FU
  enhance_image_tag: true
  static_image_support: false
